### ISSUE TITLE
Wrong scholar link

### ISSUE THREAD

**Issue by AdrienCorenflos** [MauroCE/PersonalWebsite#1]
https://github.com/MauroCE/PersonalWebsite/blob/6ea0edfbeef2e784b879c93c657e3c9b2909e4b9/content/authors/mauro/_index.md?plain=1#L58

That's not your profile :sweat_smile:

**Comment by MauroCE** [comment]
Ooops, I left the Scholar profile of the guy I forked the website from, thanks!
